### ISSUE TITLE
似乎没用哦，失效了？

### ISSUE THREAD

**Issue by hulinNeil** [kuizuo/ylgy-rush#1]
似乎没用哦，失效了？

**Comment by kuizuo** [comment]
能把具体失效的截图发下吗，这边目前测试是正常的，只不过部署到vercel上，国内网络可能无法访问

**Comment by wenge110110** [comment]
{"err_code":0,"err_msg":"","data":0}

**Comment by kuizuo** [comment]
> {"err_code":0,"err_msg":"","data":0}

这个是羊了个羊的请求返回的响应，提示这个就说明响应成功，这里我只是将响应输出以日志的方式输出出来

**Comment by hulinNeil** [comment]
响应是成功的，但是游戏中数据没有变化

**Comment by kuizuo** [comment]
> 响应是成功的，但是游戏中数据没有变化

那应该是官方把http请改了，等我抓个包重新部署一下
